GET https://skilvul-express-basic.vercel.app/api/todos
clientKey: this_is_secret

###

POST https://skilvul-express-basic.vercel.app/api/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVzdG8iLCJwYXNzd29yZCI6InF3ZTEyMyIsImlhdCI6MTY5OTUzNDEyMiwiZXhwIjoxNjk5NjIwNTIyfQ.FfHLMOfjvllpzvE7A38QEtrR74aiD3wSVS0V9bjd_9Y
Content-Type: application/json

{
  "todo": "My todo"
}

###

DELETE https://skilvul-express-basic.vercel.app/api/todos/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVzdG8iLCJwYXNzd29yZCI6InF3ZTEyMyIsImlhdCI6MTY5OTUzNDEyMiwiZXhwIjoxNjk5NjIwNTIyfQ.FfHLMOfjvllpzvE7A38QEtrR74aiD3wSVS0V9bjd_9Y
Content-Type: application/json

###

GET https://skilvul-express-basic.vercel.app/api/todos/3
Content-Type: application/json

###

PUT https://skilvul-express-basic.vercel.app/api/todos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVzdG8iLCJwYXNzd29yZCI6InF3ZTEyMyIsImlhdCI6MTY5OTUzNDEyMiwiZXhwIjoxNjk5NjIwNTIyfQ.FfHLMOfjvllpzvE7A38QEtrR74aiD3wSVS0V9bjd_9Y
Content-Type: application/json

{
  "todo": "Editted todo"
}

###

POST https://skilvul-express-basic.vercel.app/api/auth/login
Content-Type: application/json

{
  "username": "esto",
  "password": "qwe123"
}
