GET https://skilvul-express-basic.vercel.app/api/todos
clientKey: this_is_secret

###

POST https://skilvul-express-basic.vercel.app/api/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVzdG8iLCJwYXNzd29yZCI6InF3ZTEyMyIsImlhdCI6MTY5OTUzNDk4MywiZXhwIjoxNjk5NjIxMzgzfQ.DCE8d6ZbT0aIBlgIghELmSCfmQnj2qB8NTvQN5gp_c8
Content-Type: application/json

{
  "todo": "My todo"
}

###

DELETE https://skilvul-express-basic.vercel.app/api/todos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVzdG8iLCJwYXNzd29yZCI6InF3ZTEyMyIsImlhdCI6MTY5OTUzNDk4MywiZXhwIjoxNjk5NjIxMzgzfQ.DCE8d6ZbT0aIBlgIghELmSCfmQnj2qB8NTvQN5gp_c8
Content-Type: application/json

###

GET https://skilvul-express-basic.vercel.app/api/todos/3
Content-Type: application/json

###

PUT https://skilvul-express-basic.vercel.app/api/todos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVzdG8iLCJwYXNzd29yZCI6InF3ZTEyMyIsImlhdCI6MTY5OTUzNDk4MywiZXhwIjoxNjk5NjIxMzgzfQ.DCE8d6ZbT0aIBlgIghELmSCfmQnj2qB8NTvQN5gp_c8
Content-Type: application/json

{
  "todo": "Editted todo"
}

###

POST https://skilvul-express-basic.vercel.app/api/auth/login
Content-Type: application/json

{
  "username": "esto",
  "password": "qwe123"
}
