GET http://localhost:5000/api/todos
clientKey: this_is_secret

###

POST http://localhost:5000/api/todos
clientKey: this_is_secret
Content-Type: application/json

{
  "todo": "My todo"
}

###

DELETE http://localhost:5000/api/todos/1
clientKey: this_is_secret
Content-Type: application/json

###

GET http://localhost:5000/api/todos/1
clientKey: this_is_secret
Content-Type: application/json